POST http://localhost:3000/course
Content-Type: application/json

{
  "name": "Introduction to NestJS",
  "description": "Learn the basics of NestJS framework",
  "code": "18",
  "credit": 4,
  "instructor": "John Doe"
}